name: Workflow Web Manual


on:
  workflow_dispatch:
    inputs:
      filter:
        description: 'Filter type'
        required: true
        default: 'warning'
        type: choice
        options:
        - '@Smoke'
        - '@Success'
      test_type:
        description: 'Test type'
        required: true
        default: 'warning'
        type: choice
        options:
        - parallel
        - Secuencial
        
      browser_type:
        description: 'Browser Type'
        required: true
        default: 'chromeHeadless'
      
      language:
        description: 'Language used to test against'
        required: true
        default: '@EN'
        

jobs:
  testing:
    runs-on: ubuntu-latest
    container: crowdar/lippia:3.1.2.2
    
    steps:
    - uses: actions/checkout@v3
    - run: echo $TAG,
                $TESTTYPE,
                $LANG
                $BROWSERTYPE
    - run: mvn clean test -P$TESTTYPE -P$BROWSERTYPE -Dcucumber.tags="--tags $TAG"
      env:
          TAG: ${{ inputs.filter }}
          TESTTYPE: ${{ inputs.testtype }}
          browser-type: '${{ github.event.inputs.flutter_version }}'
          language: '${{ github.event.inputs.language }}'
       
    - uses: actions/upload-artifact@v3
      with:
        path: target/extent-reports/
