name: Workflow Web Manual


on:
  workflow_dispatch:
    inputs:
      filter:
        description: 'Filter type'
        required: true
        default: 'warning'
        type: choice
        options:
        - '@Success'
        - '@Smoke'
      testtype:
        description: 'Test type'
        required: true
        default: 'warning'
        type: choice
        options:
        - Secuencial
        - parallel
        
      flutter_version:
        description: 'Framework version'
        required: true
        default: '2.5.3'

      language:
        description: 'Language used to test against'
        required: true
        default: 'warning'
        type: choice
        options:
        - '@EN'
        - '@ES'
        

jobs:
  testing:
    runs-on: ubuntu-latest
    container: crowdar/lippia:3.1.2.2
    
    steps:
    - uses: actions/checkout@v3
    - run: echo $TAG,
                $TESTTYPE,
                $LANG
                $BROWSERTYPE
    - run: mvn clean test -P$TESTTYPE -P$BROWSERTYPE -Dcucumber.tags="--tags $TAG"
      env:
          TAG: ${{ inputs.filter }}
          TESTTYPE: ${{ inputs.testtype }}
          LANG: ${{ inputs.language }}
          
    - name: Set Flutter version
      uses: subosito/flutter-action@v2.2.0
        
      with:
        flutter-version: '${{ github.event.inputs.flutter_version }}


    - uses: actions/upload-artifact@v3
      with:
        path: target/extent-reports/
