name: Workflow Web Auto

on: 
 push:
  branches: [ 'main', 'master' ]

jobs:
  
  testing:
    runs-on: ubuntu-latest
    container: crowdar/lippia:3.1.2.2
    env: 
      TAG: "@Smokes"
      TESTTYPE: "parallels"
      LANG: "@EN"
      BROWSERTYPE: "chromeHeadless"
    
    steps:
    - uses: actions/checkout@v3
    - name: valores de las variables de entorno
      run: echo "TAG= "$TAG,
                "TESTTYPE= "$TESTTYPE,
                "LANG= "$LANG,
                "BROWSERTYPE= "$BROWSERTYPE
    - name: Realizando Pruebas
      continue-on-error: true
      run: mvn clean test -P$TESTTYPE -P$BROWSERTYPE -Dcucumber.tags="--tags $TAG"
    - name: Subiendo informe
      uses: actions/upload-artifact@v3
      with:
        path: target/reports/
