name: Workflow Web Manual


on:
  workflow_dispatch:
    inputs:
      test_tag:
        description: 'Test Tag'
        required: true
        default: 'warning'
        type: choice
        options:
        - '@Smoke'
        - '@Success'
        
      test_type:
        description: 'Test type'
        required: true
        default: 'warning'
        type: choice
        options:
        - parallel
        - Secuencial
        
      browser_type:
        description: 'Browser Type'
        required: true
        default: 'chromeHeadless'
      
      language:
        description: 'Language used to test against'
        required: true
        default: '@EN'        

jobs:
  testing:
    runs-on: ubuntu-latest
    container: crowdar/lippia:3.1.2.2
    env:
      TAG: '${{ github.event.inputs.test_tag }}'
      TESTTYPE: '${{ github.event.inputs.test_type }}'
      BROWSERTYPE: '${{ github.event.inputs.browser_type }}'
      LANG: '${{ github.event.inputs.language }}'
    
    steps:
    - uses: actions/checkout@v3
    - run: echo $TAG,
                $TESTTYPE,
                $LANG,
                $BROWSERTYPE
    - run: mvn clean test -P$TESTTYPE -P$BROWSERTYPE -Dcucumber.tags="--tags $TAG"
       
    - uses: actions/upload-artifact@v3
      with:
        path: target/report/
