name: Workflow Web Auto

on: 
 push:
  branches: [ '!main', '!master' ]

jobs:
  
  testing:
    runs-on: ubuntu-latest
    container: crowdar/lippia:3.1.2.2
    env: 
      TAG: "@Smoke"
      TESTTYPE: "parallel"
      LANG: "@EN"
      BROWSERTYPE: "chromeHeadless"
    
    steps:
    - uses: actions/checkout@v3
    - run: echo $TAG,
                $TESTTYPE,
                $LANG,
                $BROWSERTYPE
    - run: mvn clean test -P$TESTTYPE -P$BROWSERTYPE -Dcucumber.tags="--tags $TAG"
    - uses: actions/upload-artifact@v3
      with:
        path: target/extent-reports/
